web:
  upload_path: /Users/nieaowei/Desktop/upload
  domain: localhost:8081


server:
  port: 8081

spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  datasource:
    url: jdbc:mysql://localhost:3306/lms?characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties.hibernate.format_sql: true
  redis:
    host: 47.240.54.3
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 30000
  servlet:
    multipart:
      max-file-size: 200MB
      file-size-threshold: 200MB
      max-request-size: 200MB
